spring.application.name=synlab-backend
server.port=8080
allowed.origins=http://localhost:3000,http://localhost:4173,https://syntaxlab-lake.vercel.app,https://syntaxlab.work,https://www.syntaxlab.work
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
